language:  objective-c
os:        osx
osx_image: xcode8.3  # OS X 10.12 (https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)

sudo: required

branches:
  only:
    - master
    - /^v[\d\.]+$/

cache:
  directories:
    - vendor/bundle
    - Pods

script:
  - make build

before_deploy:
  - make build
  - make dist

deploy:
  provider: releases
  api_key:
    secure: REPLACEME
  skip_cleanup: true
  file_glob: true
  file: build/*.zip
  on:
    tags: true
    repo: creasty/Keyboard

notifications:
  email: false
